name: Release

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Application Bundle
        run: |
          mkdir -p BrowserPicker.app/Contents/MacOS
          mkdir -p BrowserPicker.app/Contents/Resources
          if [ -f "AppIcon.icns" ]; then
            cp AppIcon.icns BrowserPicker.app/Contents/Resources/
          fi
          xcrun -sdk macosx swiftc main.swift -o BrowserPicker.app/Contents/MacOS/BrowserPicker
          echo -n "APPL????" > BrowserPicker.app/Contents/PkgInfo
          cp Info.plist.example BrowserPicker.app/Contents/Info.plist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BrowserPicker
          path: BrowserPicker.app
